# Generated by Django 3.0.1 on 2019-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=6)),
                ('team_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('mob', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(choices=[('male', 'Mr.'), ('female', 'Mrs.')], default='other', max_length=6)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('college', models.CharField(max_length=30, null=True)),
                ('course', models.CharField(max_length=25, null=True)),
                ('year', models.PositiveIntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')])),
                ('city', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('skills', models.TextField()),
                ('githubUrl', models.URLField()),
                ('linkedinUrl', models.URLField()),
                ('profile_pic', models.ImageField(blank=True, default='.static/resources/hack_logo-hd.png', storage='600kb', upload_to='')),
            ],
        ),
    ]
