# Generated by Django 3.0.1 on 2019-12-29 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=6, unique=True)),
                ('team_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('mob', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(choices=[('male', 'Mr.'), ('female', 'Mrs.')], max_length=6)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('college', models.CharField(max_length=30)),
                ('course', models.CharField(blank=True, max_length=25)),
                ('year', models.PositiveIntegerField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')])),
                ('city', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('skills', models.TextField()),
                ('githubUrl', models.URLField()),
                ('linkedinUrl', models.URLField()),
                ('teamname', models.CharField(max_length=30)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.team')),
            ],
        ),
    ]
