# Generated by Django 3.0.1 on 2019-12-26 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='user',
            name='team_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registrations.team'),
            preserve_default=False,
        ),
    ]
