# Generated by Django 3.0.1 on 2019-12-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teamname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
