# Generated by Django 3.0.1 on 2019-12-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20191229_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teamname',
            field=models.CharField(max_length=20),
        ),
    ]
