# Generated by Django 3.0.1 on 2019-12-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20191229_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teamname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
