# Generated by Django 3.0.1 on 2019-12-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20191229_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('first', '1st'), ('second', '2nd'), ('third', '3rd'), ('fourth', '4th')], max_length=10),
        ),
    ]
