# Generated by Django 3.0.1 on 2019-12-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20191229_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
